"""Add some more stuff

Revision ID: 675e3a7d28da
Revises: 06a134480a9c
Create Date: 2023-06-28 14:59:46.996789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675e3a7d28da'
down_revision = '06a134480a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_cover_id_covers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_cover_id_covers'), 'covers', ['cover_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_cover_id_covers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_books_cover_id_covers', 'covers', ['cover_id'], ['id'])

    # ### end Alembic commands ###
